#!/usr/bin/env php
<?php

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), 'dev');
$debug = !$input->hasParameterOption(array('--no-debug', ''));

global $kernel;

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);

$kernel->boot();
$kernel->getContainer()->get('ekino.drupal')->initializeDrush($application);